name: CI на Github
on:
  push:
jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    steps:      
      -
        name: Checkout
        uses: actions/checkout@v2
      
      - name: sudo
        run: |
            sudo apt update && sudo apt install sudo     
            
      - # Установка docker   
        name: Set up docker
        run: |
          curl -sSL https://get.docker.com/ | sudo sh    
    
      - name: docker build
        working-directory: ./src/TUP.WebApi
        run: |
            ls -l
            cd ./TUP.WebApi
            ls -l
            docker build . -t goals-example
