name: CI на Github
on:	
  push:
jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Установка Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Docker Build
        working-directory: ./src/TUP.WebApi
        run: |
            ls -l
            docker build . -t tup
